snd-soc-kcm-objs := kcm.o kcm-chain.o
snd-soc-kcm-objs += db-user.o db-default.o
snd-soc-kcm-objs += kasobj.o
snd-soc-kcm-objs += op/utils.o op/passthr.o op/splitter.o op/resampler.o
snd-soc-kcm-objs += op/mixer.o op/delay.o op/bass.o op/peq.o op/vol-ctrl.o
snd-soc-kcm-objs += op/aec-ref.o op/cvc-send.o op/cvc-recv.o

obj-$(CONFIG_SND_SOC_SIRF_KALIMBA) += snd-soc-kcm.o
