snd-soc-kcm-objs := kcm.o kcm-chain.o
snd-soc-kcm-objs += db-user.o db-default.o
snd-soc-kcm-objs += kasobj.o
snd-soc-kcm-objs += op/utils.o op/passthr.o op/splitter.o op/resampler.o

obj-$(CONFIG_SND_SOC_SIRF_KALIMBA) += snd-soc-kcm.o
