#ifndef _SIRF_ATLAS7_CODEC_H
#define _SIRF_ATLAS7_CODEC_H

#define ANA_PMUCTL1						0x20
#define ANA_PMUCTL2						0x24

#define AUDIO_REF_CTRL					0x38
#define AUDIO_REF_CTRL2					0x3C

#define AUDIO_REGS_CLK_CTRL				0x44
#define AUDIO_KCODEC_CTRL				0x48
#define AUDIO_DAC_CTRL					0x54
#define AUDIO_CTRL_SPARE_0				0x58
#define AUDIO_ANA_DAC_CTRL0				0x60
#define AUDIO_ANA_REF_CTRL0				0x64

#define AUDIO_ANA_ADC_CTRL0				0x68
#define AUDIO_ANA_ADC_CTRL1				0x6C
#define AUDIO_ANA_ADC_CTRL2				0x70
#define AUDIO_ANA_ADC_CTRL3				0x74
#define AUDIO_ANA_ADC_CTRL4				0x78
#define AUDIO_ANA_CAL_CTRL0				0x7C

#define KCODEC_ADC_A_GAIN				0xA0
#define KCODEC_ADC_A_SAMP_RATE			0xAC
#define KCODEC_ADC_B_GAIN				0xBC
#define KCODEC_ADC_B_SAMP_RATE			0xCC

#define KCODEC_CONFIG_EXTENSION2		0xF8
#define KCODEC_CONFIG2_EXTENSION2		0x110
#define KCODEC_CONFIG					0x150
#define KCODEC_CONFIG2					0x158
#define KCODEC_DAC_A_GAIN				0x164
#define KCODEC_DAC_A_SAMP_RATE			0x16C
#define KCODEC_DAC_B_GAIN				0x174
#define KCODEC_DAC_B_SAMP_RATE			0x17C
#define KCODEC_DAC_C_GAIN				0x184
#define KCODEC_DAC_C_SAMP_RATE			0x188
#define KCODEC_DAC_D_GAIN				0x190
#define KCODEC_DAC_D_SAMP_RATE			0x194

#define AUDIO_PLL_CTRL_1				0x230
#define AUDIO_PLL_STATUS				0x250

#define KCODEC_WARP_UPDATE				0x368

#define PMUCTL1_LDO_VAUDIO1V8_EN		(1 << 1)
#define PMUCTL1_VOUT_SEL_LDO_VAUDIO1V8	(1 << 2)
#define PMUCTL1_LDO_VAUDIO2V5_EN		(1 << 4)
#define PMUCTL1_VOUT_SEL_LDO_VAUDIO2V5	(1 << 5)

#define CLKSYNR_NRST					(1 << 12)

#define PMUCTRL2_VBG_TRIM				0xF
#define PMUCTRL2_IREF_TRIM				(0x7 << 4)

#define PMUCTRL2_VBG_TRIM_0XF			0XF

#define AUDIO_ANA_REF_AUDBIAS_IREF_EN			1
#define AUDIO_ANA_REF_AUDBIAS_IREF_TRIM_SHIFT	1
#define AUDIO_ANA_REF_AUDBIAS_VAG_RX_EN			(1 << 4)
#define AUDIO_ANA_REF_AUDBIAS_VAG_TX_EN			(1 << 5)
#define AUDIO_ANA_REF_AUDBIAS_IREF_TRIM_MASK	(0x7 << 1)

#define AUDIO_REF_BIAS_BG_VTH_TRIM_MASK			0xF
#define AUDIO_REF_BIAS_BG_PTAT_TRIM_MASK		(0xF << 4)
#define AUDIO_REF_BIAS_BG_PTAT_TRIM_SHIFT		4

#define AUDIO_REF_BOOST_EN_DACBUFF_IREF_MASK	0x3

#define KCODEC_DAC_EN					1

/* fields of register KCODEC_CONFIG */
#define KCODEC_ADC_EN					(1 << 1)
#define KCODEC2_CONFIG_ADC_A_EN			(1<<10)
#define KCODEC2_CONFIG_ADC_B_EN			(1<<11)

#define KCODEC_ADC_A_SAMP_RATE			0xAC
#define KCODEC_ADC_B_SAMP_RATE			0xCC

/* fields of register AUDIO_ANA_REF_CTRL0 */
#define AUDIO_ANA_REF_AUDBIAS_IREF_EN		1
#define AUDIO_ANA_REF_AUDBIAS_IREF_TRIM		(7<<1)
#define AUDIO_ANA_REF_AUDBIAS_VAG_TSADC_EN  (1<<6)
#define AUDIO_ANA_REF_MICBIAS_EN			(1<<7)

/*fields of register AUDIO_REGS_CLK_CTRL */
#define ADC_CLK_EN							(3<<4)
#define AUDIO_ANA_CAL_CLK_EN				(1<<13)

/*fields of register AUDIO_ANA_ADC_CTRL0 */
#define AUDIO_ANA_ADC_SW					0xffff

/*fields of register AUDIO_ANA_ADC_CTRL1 */
#define AUDIO_ANA_ADC_CH12_CCAL_SEL			(0xf<<8)

/*fields of register AUDIO_ANA_ADC_CTRL2 */
#define AUDIO_ANA_ADC_CH1_EN				1
#define AUDIO_ANA_ADC_CH1_DITHER_EN			(1<<1)
#define AUDIO_ANA_ADC_CH1_DWA_EN			(1<<2)
#define AUDIO_ANA_ADC_CH1_GAIN_SEL			(0xf<<3)

/*fields of register AUDIO_ANA_ADC_CTRL3 */
#define AUDIO_ANA_ADC_CH2_EN				1
#define AUDIO_ANA_ADC_CH2_DITHER_EN			(1<<1)
#define AUDIO_ANA_ADC_CH2_DWA_EN			(1<<2)
#define AUDIO_ANA_ADC_CH2_GAIN_SEL			(0xf<<3)

/*fields of register AUDIO_ANA_CAL_CTRL0 */
#define AUDIO_ANA_CAL_ADC_EN				1


#define DAC_BASE_SMAPLE_RATE_44K1			0
#define DAC_BASE_SMAPLE_RATE_48K0			1
#define DAC_BASE_SMAPLE_RATE_32K0			2
#define DAC_BASE_SMAPLE_RATE_40K0			3
#define DAC_BASE_SMAPLE_RATE_96K0			4
#define DAC_BASE_SMAPLE_RATE_192K0			5

#define KCODEC_DAC_SELECT_EXT					(1 << 5)
#define KCODEC_DAC_EXT_BASE_SAMP_RATE_SHIFT		6
#define KCODEC_DAC_EXTENDED_BASE_SAMP_RATE_MASK	(0xF << 6)

#define ADC_SAMPLE_RATE_08K				0
#define ADC_SAMPLE_RATE_11K				1
#define ADC_SAMPLE_RATE_12K				10
#define ADC_SAMPLE_RATE_16K				2
#define ADC_SAMPLE_RATE_22K				3
#define ADC_SAMPLE_RATE_24K				4
#define ADC_SAMPLE_RATE_32K				5
#define ADC_SAMPLE_RATE_44K				6
#define ADC_SAMPLE_RATE_48K				8
#define ADC_SAMPLE_RATE_96K				9

#define KCODEC_CONFIG_DEM_DITHER_CFG_MASK		0x1F
#define KCODEC_CONFIG_DEM_DITHER_CFG_SHIFT		0

#define TXADC_IREF_EN					1

#define AUDIO_ANA_CTRL_ADC_EN			1

#define AUDIO_GAIN_MASK						0x1FF
#define AUDIO_ANA_ADC_MICAMP_GAIN_SEL_MASK	(0xf << 3)
#define AUDIO_ANA_ADC_MICAMP_GAIN			(10 << 3)
#endif /* _SIRF_ATLAS7_CODEC_H */
