sirfsoc_vip-objs                    := cvd.o vip_capture.o
obj-$(CONFIG_VIDEO_SIRFSOC_VIP)   += sirfsoc_vip.o
obj-$(CONFIG_VIDEO_SIRFSOC_REARVIEW)   += rearview.o
obj-$(CONFIG_VIDEO_SIRFSOC_VOUT)  += sirfsoc_vout.o
