
# Makefile for CSR vip controller driver.

obj-$(CONFIG_VIDEO_SIRFSOC_VIP)   += sirfsoc_vip.o

sirfsoc_vip-objs                    := sirfsoc_vip_src.o CspSocVip.o
sirfsoc_vip-$(CONFIG_VIDEO_SIRFSOC_VIP)    := $(sirfsoc_vip-objs)
