snd-soc-sirf-objs := sirf-pcm.o
snd-soc-sirf-soc-inner-objs := sirf-soc-inner.o 
snd-soc-sirf-inner-objs := sirf-inner.o

obj-$(CONFIG_SND_SIRF_SOC) += snd-soc-sirf.o
obj-$(CONFIG_SND_SIRF_SOC_INNER) += snd-soc-sirf-soc-inner.o
obj-$(CONFIG_SND_SIRF_INNER) += snd-soc-sirf-inner.o
