snd-soc-sirf-audio-port-objs := sirf-audio-port.o
snd-soc-sirf-audio-objs := sirf-audio.o
snd-soc-sirf-usp-objs := sirf-usp.o
snd-soc-sirf-i2s-objs := sirf-i2s.o
snd-soc-sirf-bt-sco-objs := sirf-bt-sco.o
snd-soc-sirf-hdmi-objs := sirf-hdmi.o

obj-$(CONFIG_SND_SOC_SIRF_AUDIO_PORT) += snd-soc-sirf-audio-port.o
obj-$(CONFIG_SND_SOC_SIRF_AUDIO) += snd-soc-sirf-audio.o
obj-$(CONFIG_SND_SOC_SIRF_USP) += snd-soc-sirf-usp.o
obj-$(CONFIG_SND_SOC_SIRF_I2S) += snd-soc-sirf-i2s.o
obj-$(CONFIG_SND_SOC_SIRF_BT_SCO) += snd-soc-sirf-bt-sco.o
obj-$(CONFIG_SND_SOC_SIRF_HDMI) += snd-soc-sirf-hdmi.o
