obj-$(CONFIG_SIRF_VDSS) += sirfsoc_vdss.o
# Core DSS files
sirfsoc_vdss-y := core.o lcdc.o display.o output.o \
	layer_screen.o vpp.o lvdsc.o layer-sysfs.o \
	screen-sysfs.o \

ccflags-$(CONFIG_SIRF_VDSS_DEBUG) += -DDEBUG
